# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [26]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [27]:
csv_file = os.path.join('cityweather.csv')
city_df = pd.read_csv(csv_file)
city_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
0,5866583,Saint Paul Harbor,US,57.79,-152.41,35.60,74,20,10.29
1,3372707,Ribeira Grande,PT,38.52,-28.70,61.63,71,99,10.29
2,1006984,East London,ZA,-33.02,27.91,67.95,75,81,10.54
3,3137469,Sørland,NO,67.67,12.69,37.81,77,94,8.70
4,1106677,Bambous Virieux,MU,-20.34,57.76,77.00,88,40,11.41
...,...,...,...,...,...,...,...,...,...
567,1214488,Meulaboh,ID,4.14,96.13,76.05,84,100,5.35
568,2098329,Daru,PG,-9.08,143.21,83.19,82,87,9.82
569,1215502,Banda Aceh,ID,5.56,95.32,78.48,79,100,5.19
570,1863978,Nishifukuma,JP,33.77,130.47,38.05,48,75,16.11
571,2109528,Buala,SB,-8.14,159.59,84.99,75,88,7.31

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
gmaps.configure(api_key=g_key)

In [28]:
cities = city_df[['Lat', 'Lng']]
humidity = city_df['Humidity']
heat_map = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
heat_layer = gmaps.heatmap_layer(cities, weights=humidity, dissipating=False)
heat_layer.max_intensity = 100
heat_layer.point_radius=5

heat_map.add_layer(heat_layer)
heat_map

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [11]:
ideal_cities_df = city_df[(city_df['Temperature'] < 80) & (city_df['Temperature'] < 70)]
ideal_cities_df = ideal_cities_df[ideal_cities_df['Wind Speed'] < 10]
ideal_cities_df = ideal_cities_df[ideal_cities_df['Clouds'] == 0]
hotel_df = ideal_cities_df
hotel_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
7,2075265,Busselton,AU,-33.65,115.33,60.26,73,0,1.01
16,3831208,Qaanaaq,GL,77.48,-69.36,-0.26,67,0,7.67
30,1507390,Dikson,RU,73.51,80.55,-21.35,85,0,2.17
40,3366880,Hermanus,ZA,-34.42,19.23,53.01,92,0,9.08
50,3418910,Upernavik,GL,72.79,-56.15,13.01,78,0,6.64
56,286621,Salalah,OM,17.02,54.09,69.80,52,0,6.93
64,1015776,Bredasdorp,ZA,-34.53,20.04,55.40,82,0,2.24
72,990930,Kimberley,ZA,-28.73,24.76,64.40,72,0,5.82
116,1254046,Tura,IN,25.52,90.22,58.57,86,0,3.24
132,1529484,Kumul,CN,42.80,93.45,12.40,75,0,1.21
133,4012707,Cosalá,MX,24.41,-106.69,68.77,57,0,3.18
139,5391791,San Clemente,US,33.43,-117.61,64.06,62,0,4.00
151,2034615,Tahe,CN,52.33,124.73,-12.66,80,0,4.21
153,2070998,Geraldton,AU,-28.77,114.60,68.00,72,0,8.05
185,141736,Bam,IR,29.11,58.36,43.65,53,0,2.33
197,3421765,Nanortalik,GL,60.14,-45.24,26.91,88,0,9.08
204,2751455,Gemeente Loon op Zand,NL,51.64,5.05,42.03,93,0,5.82
208,3430863,Mar del Plata,AR,-38.00,-57.56,59.77,51,0,5.82
212,1524801,Shīeli,KZ,44.17,66.75,18.66,86,0,4.23
213,1919088,Yongchang,CN,30.04,119.73,33.66,76,0,2.46
217,1255870,Sohna,IN,28.25,77.07,48.20,93,0,5.61
224,111421,Zarand,IR,30.81,56.56,42.91,61,0,3.65
227,1786657,Yinchuan,CN,38.47,106.27,15.06,77,0,3.27
276,2019118,Nizhniy Tsasuchey,RU,50.52,115.13,-3.19,87,0,3.24
287,1510377,Belyy Yar,RU,53.60,91.39,21.20,57,0,4.47
289,110690,Faya,SA,18.39,42.45,50.90,71,0,3.36
291,1524889,Chardara,KZ,41.25,67.97,28.87,91,0,5.06
293,3128760,Barcelona,ES,41.39,2.16,52.95,81,0,5.82
327,417594,Shahreza,IR,32.03,51.88,39.88,67,0,2.08
332,2381972,Adrar,MR,20.50,-10.07,67.03,25,0,7.09
335,1497543,Nizhnevartovsk,RU,60.93,76.55,-14.80,75,0,6.71
348,6929460,Panzhihua,CN,26.59,101.71,47.93,74,0,1.61
364,2034440,Tieli,CN,46.95,128.05,-15.11,84,0,4.03
389,3855075,General Pico,AR,-35.66,-63.76,69.42,21,0,9.42
397,3842670,Olavarría,AR,-36.89,-60.32,61.65,30,0,0.92
414,1179450,Dunyapur,PK,29.80,71.72,42.80,87,0,4.70
417,2038665,Alihe,CN,50.57,123.72,-12.23,79,0,3.94
419,3128795,Barbastro,ES,42.04,0.13,38.70,100,0,3.36
426,2425791,Kibala,TD,9.11,18.35,69.80,68,0,3.58
438,1282898,Pokhara,NP,28.23,83.98,53.31,33,0,5.37
440,2541479,Nador,MA,35.17,-2.93,51.94,71,0,1.12
445,259289,Corinth,GR,37.94,22.96,51.01,72,0,3.42
466,686090,Asău,RO,46.43,26.40,34.00,100,0,2.68
474,187585,Marsabit,KE,2.33,37.99,66.76,55,0,9.26
484,2537881,Safi,MA,32.30,-9.24,61.39,83,0,6.55
493,3359736,Vredendal,ZA,-31.67,18.50,61.32,67,0,1.07
499,3899361,Arica,CL,-18.48,-70.30,68.00,77,0,6.93
505,2034400,Tongliao,CN,43.61,122.27,-10.97,83,0,6.76
506,124193,Meybod,IR,32.25,54.02,37.40,74,0,4.70
515,290340,Manama,BH,26.22,50.58,66.20,77,0,3.36
519,1522751,Kentau,KZ,43.52,68.51,22.03,76,0,2.26
526,1271934,Fatehābād,IN,29.52,75.45,48.34,48,0,4.79
547,3892454,Diego de Almagro,CL,-26.37,-70.05,62.67,47,0,3.51
552,1266475,Kishtwār,IN,33.32,75.77,28.80,71,0,5.28
559,2037799,Datong,CN,40.09,113.29,5.11,81,0,2.64

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [12]:
hotel_df['Hotel Name'] = ""
hotel_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
7,2075265,Busselton,AU,-33.65,115.33,60.26,73,0,1.01,
16,3831208,Qaanaaq,GL,77.48,-69.36,-0.26,67,0,7.67,
30,1507390,Dikson,RU,73.51,80.55,-21.35,85,0,2.17,
40,3366880,Hermanus,ZA,-34.42,19.23,53.01,92,0,9.08,
50,3418910,Upernavik,GL,72.79,-56.15,13.01,78,0,6.64,
56,286621,Salalah,OM,17.02,54.09,69.80,52,0,6.93,
64,1015776,Bredasdorp,ZA,-34.53,20.04,55.40,82,0,2.24,
72,990930,Kimberley,ZA,-28.73,24.76,64.40,72,0,5.82,
116,1254046,Tura,IN,25.52,90.22,58.57,86,0,3.24,
132,1529484,Kumul,CN,42.80,93.45,12.40,75,0,1.21,
133,4012707,Cosalá,MX,24.41,-106.69,68.77,57,0,3.18,
139,5391791,San Clemente,US,33.43,-117.61,64.06,62,0,4.00,
151,2034615,Tahe,CN,52.33,124.73,-12.66,80,0,4.21,
153,2070998,Geraldton,AU,-28.77,114.60,68.00,72,0,8.05,
185,141736,Bam,IR,29.11,58.36,43.65,53,0,2.33,
197,3421765,Nanortalik,GL,60.14,-45.24,26.91,88,0,9.08,
204,2751455,Gemeente Loon op Zand,NL,51.64,5.05,42.03,93,0,5.82,
208,3430863,Mar del Plata,AR,-38.00,-57.56,59.77,51,0,5.82,
212,1524801,Shīeli,KZ,44.17,66.75,18.66,86,0,4.23,
213,1919088,Yongchang,CN,30.04,119.73,33.66,76,0,2.46,
217,1255870,Sohna,IN,28.25,77.07,48.20,93,0,5.61,
224,111421,Zarand,IR,30.81,56.56,42.91,61,0,3.65,
227,1786657,Yinchuan,CN,38.47,106.27,15.06,77,0,3.27,
276,2019118,Nizhniy Tsasuchey,RU,50.52,115.13,-3.19,87,0,3.24,
287,1510377,Belyy Yar,RU,53.60,91.39,21.20,57,0,4.47,
289,110690,Faya,SA,18.39,42.45,50.90,71,0,3.36,
291,1524889,Chardara,KZ,41.25,67.97,28.87,91,0,5.06,
293,3128760,Barcelona,ES,41.39,2.16,52.95,81,0,5.82,
327,417594,Shahreza,IR,32.03,51.88,39.88,67,0,2.08,
332,2381972,Adrar,MR,20.50,-10.07,67.03,25,0,7.09,
335,1497543,Nizhnevartovsk,RU,60.93,76.55,-14.80,75,0,6.71,
348,6929460,Panzhihua,CN,26.59,101.71,47.93,74,0,1.61,
364,2034440,Tieli,CN,46.95,128.05,-15.11,84,0,4.03,
389,3855075,General Pico,AR,-35.66,-63.76,69.42,21,0,9.42,
397,3842670,Olavarría,AR,-36.89,-60.32,61.65,30,0,0.92,
414,1179450,Dunyapur,PK,29.80,71.72,42.80,87,0,4.70,
417,2038665,Alihe,CN,50.57,123.72,-12.23,79,0,3.94,
419,3128795,Barbastro,ES,42.04,0.13,38.70,100,0,3.36,
426,2425791,Kibala,TD,9.11,18.35,69.80,68,0,3.58,
438,1282898,Pokhara,NP,28.23,83.98,53.31,33,0,5.37,
440,2541479,Nador,MA,35.17,-2.93,51.94,71,0,1.12,
445,259289,Corinth,GR,37.94,22.96,51.01,72,0,3.42,
466,686090,Asău,RO,46.43,26.40,34.00,100,0,2.68,
474,187585,Marsabit,KE,2.33,37.99,66.76,55,0,9.26,
484,2537881,Safi,MA,32.30,-9.24,61.39,83,0,6.55,
493,3359736,Vredendal,ZA,-31.67,18.50,61.32,67,0,1.07,
499,3899361,Arica,CL,-18.48,-70.30,68.00,77,0,6.93,
505,2034400,Tongliao,CN,43.61,122.27,-10.97,83,0,6.76,
506,124193,Meybod,IR,32.25,54.02,37.40,74,0,4.70,
515,290340,Manama,BH,26.22,50.58,66.20,77,0,3.36,
519,1522751,Kentau,KZ,43.52,68.51,22.03,76,0,2.26,
526,1271934,Fatehābād,IN,29.52,75.45,48.34,48,0,4.79,
547,3892454,Diego de Almagro,CL,-26.37,-70.05,62.67,47,0,3.51,
552,1266475,Kishtwār,IN,33.32,75.77,28.80,71,0,5.28,
559,2037799,Datong,CN,40.09,113.29,5.11,81,0,2.64,

In [22]:
for index, row in hotel_df.iterrows():
    try:
        
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

        params = {
        "keyword": "hotel",
        "radius": 5000,
        "key": g_key,
        }


        lat = row['Lat']
        lng = row['Lng']

        params['location'] = f"{lat}, {lng}"

        hotel_data = requests.get(base_url, params=params).json()
        
        hotel_df.loc[index, "Hotel Name"] = hotel_data["results"][0]["name"]
        
    except IndexError:
        
        hotel_df.loc[index, "Hotel Name"] = "NaN"
        
hotel_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
7,2075265,Busselton,AU,-33.65,115.33,60.26,73,0,1.01,Esplanade Hotel
16,3831208,Qaanaaq,GL,77.48,-69.36,-0.26,67,0,7.67,Qaanaaq Hotel
30,1507390,Dikson,RU,73.51,80.55,-21.35,85,0,2.17,NaN
40,3366880,Hermanus,ZA,-34.42,19.23,53.01,92,0,9.08,Misty Waves Boutique Hotel
50,3418910,Upernavik,GL,72.79,-56.15,13.01,78,0,6.64,Café de Upernavik
56,286621,Salalah,OM,17.02,54.09,69.80,52,0,6.93,InterCityHotel Salalah
64,1015776,Bredasdorp,ZA,-34.53,20.04,55.40,82,0,2.24,Victoria Hotel - Bredasdorp
72,990930,Kimberley,ZA,-28.73,24.76,64.40,72,0,5.82,Kimberley Anne Hotel
116,1254046,Tura,IN,25.52,90.22,58.57,86,0,3.24,Hotel Polo Orchid
132,1529484,Kumul,CN,42.80,93.45,12.40,75,0,1.21,Haoli Business Hotel
133,4012707,Cosalá,MX,24.41,-106.69,68.77,57,0,3.18,Hotel Real del Conde
139,5391791,San Clemente,US,33.43,-117.61,64.06,62,0,4.00,Holiday Inn Express San Clemente N - Beach Area
151,2034615,Tahe,CN,52.33,124.73,-12.66,80,0,4.21,诚信商务酒店
153,2070998,Geraldton,AU,-28.77,114.60,68.00,72,0,8.05,Ocean Centre Hotel
185,141736,Bam,IR,29.11,58.36,43.65,53,0,2.33,Parsian Bam Hotel
197,3421765,Nanortalik,GL,60.14,-45.24,26.91,88,0,9.08,Hotel Kap Farvel
204,2751455,Gemeente Loon op Zand,NL,51.64,5.05,42.03,93,0,5.82,Hotel 't Peperhuys
208,3430863,Mar del Plata,AR,-38.00,-57.56,59.77,51,0,5.82,Altos de Güemes Hotel
212,1524801,Shīeli,KZ,44.17,66.75,18.66,86,0,4.23,Hotel Элита
213,1919088,Yongchang,CN,30.04,119.73,33.66,76,0,2.46,Xixiangji Inn
217,1255870,Sohna,IN,28.25,77.07,48.20,93,0,5.61,Prakash Hotel
224,111421,Zarand,IR,30.81,56.56,42.91,61,0,3.65,تالار قصر زرند(پردیس)
227,1786657,Yinchuan,CN,38.47,106.27,15.06,77,0,3.27,Kempinski Hotel Yinchuan
276,2019118,Nizhniy Tsasuchey,RU,50.52,115.13,-3.19,87,0,3.24,NaN
287,1510377,Belyy Yar,RU,53.60,91.39,21.20,57,0,4.47,NaN
289,110690,Faya,SA,18.39,42.45,50.90,71,0,3.36,NaN
291,1524889,Chardara,KZ,41.25,67.97,28.87,91,0,5.06,"Gostinitsa ""Kyzyl Zhar"""
293,3128760,Barcelona,ES,41.39,2.16,52.95,81,0,5.82,Hotel SB Glow
327,417594,Shahreza,IR,32.03,51.88,39.88,67,0,2.08,هتل باغ اناری
332,2381972,Adrar,MR,20.50,-10.07,67.03,25,0,7.09,NaN
335,1497543,Nizhnevartovsk,RU,60.93,76.55,-14.80,75,0,6.71,Park-Hotel
348,6929460,Panzhihua,CN,26.59,101.71,47.93,74,0,1.61,Chuanhui Grand Hotel
364,2034440,Tieli,CN,46.95,128.05,-15.11,84,0,4.03,Jinlidu Hotel
389,3855075,General Pico,AR,-35.66,-63.76,69.42,21,0,9.42,Hotel Pico
397,3842670,Olavarría,AR,-36.89,-60.32,61.65,30,0,0.92,Hotel Santa Rosa
414,1179450,Dunyapur,PK,29.80,71.72,42.80,87,0,4.70,Sahil Hotel
417,2038665,Alihe,CN,50.57,123.72,-12.23,79,0,3.94,Great Xianbei Hotel Inner Mongolia
419,3128795,Barbastro,ES,42.04,0.13,38.70,100,0,3.36,Hotel Clemente
426,2425791,Kibala,TD,9.11,18.35,69.80,68,0,3.58,Hôtel des Chasses
438,1282898,Pokhara,NP,28.23,83.98,53.31,33,0,5.37,Swiss International Hotel Sarowar
440,2541479,Nador,MA,35.17,-2.93,51.94,71,0,1.12,Hotel Mediterranee
445,259289,Corinth,GR,37.94,22.96,51.01,72,0,3.42,Club Hotel Casino Loutraki
466,686090,Asău,RO,46.43,26.40,34.00,100,0,2.68,Pensiunea Sophia
474,187585,Marsabit,KE,2.33,37.99,66.76,55,0,9.26,Jirime Hotel & Resort
484,2537881,Safi,MA,32.30,-9.24,61.39,83,0,6.55,Hôtel al Madina
493,3359736,Vredendal,ZA,-31.67,18.50,61.32,67,0,1.07,River Lodge
499,3899361,Arica,CL,-18.48,-70.30,68.00,77,0,6.93,Hotel Apacheta
505,2034400,Tongliao,CN,43.61,122.27,-10.97,83,0,6.76,Country Garden Phoenix Hotel Tongliao
506,124193,Meybod,IR,32.25,54.02,37.40,74,0,4.70,Traditional Hotel Restaurant Haji Malek
515,290340,Manama,BH,26.22,50.58,66.20,77,0,3.36,Four Seasons Hotel Bahrain Bay
519,1522751,Kentau,KZ,43.52,68.51,22.03,76,0,2.26,Homestay Betty's B&B
526,1271934,Fatehābād,IN,29.52,75.45,48.34,48,0,4.79,Hotel Park View By Amatra
547,3892454,Diego de Almagro,CL,-26.37,-70.05,62.67,47,0,3.51,Hotel Panorama
552,1266475,Kishtwār,IN,33.32,75.77,28.80,71,0,5.28,Hotel Phoenix International
559,2037799,Datong,CN,40.09,113.29,5.11,81,0,2.64,Datong Weidu International Hotel

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [25]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
heat_map.add_layer(markers)
heat_map
# Display figure

Figure(layout=FigureLayout(height='420px'))